- name: Déploiement ToDoApp sur EC2
  hosts: aws
  become: true
  tasks:
    - name: Installer nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copier l'application
      copy:
        src: ./index.html
        dest: /var/www/html/index.html
