- name: Déploiement ToDoApp sur EC2
  hosts: aws
  become: true
  tasks:
    - name: Installer nginx
      yum:
        name: nginx
        state: present
        update_cache: yes

    - name: Déployer la page
      copy:
        src: ./index.html
        dest: /usr/share/nginx/html/index.html

    - name: Activer et démarrer nginx
      systemd:
        name: nginx
        state: started
        enabled: true
