- name: Déploiement ToDoApp sur EC2
  hosts: aws
  become: true
  tasks:
    - name: Installer nginx
      yum:
        name: nginx
        state: present
        update_cache: yes

    - name: Déployer la page
      copy:
        dest: /usr/share/nginx/html/index.html
        owner: root
        group: root
        mode: '0644'
        content: |
          <!doctype html>
          <html><head><meta charset="utf-8"><title>TodoApp AWS</title></head>
          <body><h1>Déployé via GitHub Actions + Ansible 🚀</h1></body></html>

    - name: Activer et démarrer nginx
      systemd:
        name: nginx
        state: started
        enabled: true
